# Generated by Django 3.2.7 on 2021-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
